apiVersion: v1
kind: Service
metadata:
  name: zoo
spec:
  ports:
  - port: 2888
    name: peer
  - port: 3888
    name: leader-election
  - name: main
    port: 2181
    nodePort: 30090
#  clusterIP: None
  selector:
    app: zookeeper
  type: NodePort 
